name: SampleStaticLibraryB
sln_path: Project/windows/SampleStaticLibraryB.sln
dependencies:
  - project: masahikotsujita/SampleStaticLibraryA
    version: ^1.0.0
artifacts:
  include_headers:
    - Include/*
  link_libraries:
    - Dist/SampleStaticLibraryB_${PLATFORM}_${CONFIGURATION}.lib
