name: SampleStaticLibraryB
sln_path: Project/windows/SampleStaticLibraryB.sln
dependencies:
  - masahikotsujita/SampleStaticLibraryA
artifacts:
  include_headers:
    - Include/*
  link_libraries:
    - Dist/SampleStaticLibraryB_${PLATFORM}_${CONFIGURATION}.lib
